version: '3'
services:
  mariadb:
    build: ./mariadb
    restart: on-failure
    hostname: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
    networks:
      - default

  msgsrv:
    build: ./msgsrv
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - "5000:5000"
    networks:
      - default
